### ISSUE TITLE
[3.0] Support Polymer 3.0

### ISSUE THREAD

**Issue by t2ym** [t2ym/i18n-behavior#67]
[3.0] Support Polymer 3.0

Linked with https://github.com/t2ym/i18n-element/issues/58

## Status
- WIP in [`3.0-develop`](https://github.com/t2ym/i18n-behavior/tree/3.0-develop) branch
  - Now merged into [`master`](https://github.com/t2ym/i18n-behavior/tree/master) branch
- Release Candidate Version: `3.0.0-rc.1` with `@next` tag
  - Install with `npm install i18n-behavior@3.0.0-rc.1` or `npm install i18n-behavior@next`

## Tasks
- [x] Update README
  - [x] Rearrange roughly for 3.0
  - [ ] TBD
- [x] Support docs and demo on `iron-component-page`
  - [x] `iron-component-page` at `/components/i18n-behavior/`
  - [x] demo at `/components/i18n-behavior/demo/preprocess/`
  - [x] `npm run build:demo` to build `esm-bunbundled|esm-bundled|es6-bundled|es5-bundled` for demo at `/demo/preprocess/`
  - [x] `npm run build:docs` to build `esm-unbundled` for gh-pages
    - [ ] namespaces are not recognized
- [x] Code Cleanup
  - [x] `i18n-dom-bind` definition for Polymer 1.x
  - [x] Remove unnecessary closures
  - [x] Remove `ElementMixin` from `i18n-behavior.js`
    - Used only for detection of Polymer version 2.0 or later as a truthy value
  - [x] Remove `Polymer$0` from `i18n-behavior.js`
    - `Polymer$0` function is no longer used in `i18n-behavior.js`
  - [x] Remove `window.ShadowDOMPolyfill` reference
    - `ShadowDOMPolyfill` is no longer used in the current `ShadyDOM` polyfill
  - [x] Drop Safari 7 support
    - [x] Remove unreachable code as `extraWhiteSpaceNode` is always `false`
  - [x] Remove unreachable code as `isStandardPropertyConfigurable` is always `false`
    - [x] `_updateEffectiveLang` property in the original info object is always overridden and should be removed
  - [x] Drop support for HTML Imports
  - [x] Drop fixes only for Polymer 1.x
  - [x] Remove dependency on `(Polymer.)Base`
  - [x] Remove dependency on `(Polymer.)dom`
  - [x] Merge mandatory monkey patches into the original code
  - [x] Remove unreachable code for redundant `i18n-dom-bind` initialization
  - [x] Remove unnecessary fix for Polymer 1.x
  - [x] Remove unreachable code with `DomModule.import()`
  - [x] Remove unreachable code on missing `this.__data`, which has always been initialized
  - [x] Remove unreachable code on missing `this._fetchStatus`, which has always been initialized at `registered` callback
  - [x] Remove unnecessary comments
  - [x] Adjust indentation for `i18n-behavior.js`
  - [x] Remove unnecessary imports from `i18n-attr-repo.js`
  - [x] Remove unnecessary comments from `i18n-preference.js`
  - [x] Adjust indentation for `i18n-preference.js`
- [ ] Design Issues
  - [ ] `lang` property/attribute becomes empty if the fallback language is `""`
    - [ ] Design 1: The value should be the `templateDefaultLang` value, that is, `"en"` in normal cases
    - [ ] Design 2: Remove the `lang` attribute if the `lang` property is empty
    - [ ] Lots of TESTS have to be updated. Hmm.
  - [x] Where to put `templateDefaultLang`
    - [x] Wrap with a function like this: `_template: ((t) => { t.setAttribute("lang", "fr"); return t; })(html``...``)`
  - [x] How to preprocess embedded HTML templates
    - [x] Extract html``...``
  - [x] How to put `<i18n-attr-repo>`; Following the method by `polymer-modulizer`
```javascript
    const i18nAttrRepoContainer = document.createElement('template');
    i18nAttrRepoContainer.innerHTML = `<i18n-attr-repo>
      <template id="custom">
        <input i18n-target-attr="$">
      </template>
    </i18n-attr-repo>`;
    document.head.appendChild(i18nAttrRepoContainer.content);
```
  - [ ] TBD...
- [x] Conversion
  - [x] `BehaviorsStore.I18nBehavior` (`i18n-behavior.js`)
    - [x] As a global variable
    - [x] Export as `I18nBehavior`
    - [x] Legacy Syntax
    - Note: `i18n-dom-bind` will be moved to `i18n-element` package
  - [x] `i18n-attr-repo` (`i18n-attr-repo.js`)
    - Test results are not well checked manually
  - [x] `i18n-preference` (`i18n-preference.js`)
  - [x] `BehaviorsStore.I18nControllerBehavior` (`i18n-controller-behavior.js`)
    - [x] As a global variable
    - [x] Export as `I18nControllerBehavior` from `i18n-behavior.js`
    - [x] Export as `I18nControllerBehavior` from `i18n-controller-behavior.js`
    - Not Tested
- [x] demo
  - [x] `i18n-behavior-demo`
  - [x] `demo/gulpfile.js` - `cd demo; ../node_modules/.bin/gulp`
    - [x] Scan
      - [x] Imperative addition of `<i18n-attr-repo>` element
      - [x] Unmodulize `<i18n-attr-repo>` element
    - [x] Preprocess
      - [x] Extract JSON
      - [x] Mutate templates in ES Modules
        - Backquotes in HTML templates must be encoded as the HTML entity `&#96;`
        - No compound literals like `${X}` are allowed in HTML templates.  They must be simple strings.
        - Basename of the module must be the same as the custom element name, that is, `i18n-behavior-demo.js` must define the custom element `<i18n-behavior-demo>`
    - [x] Leverage JSON
    - [x] `bundle.*.json`
    - [x] Feedback
    - [x] Export/Import XLIFF
    - [x] Add `locales` task
      - [x] `gulp locales --targets="{space separated list of target locales}"`
  - [x] `polymer build` support
    - [x] Search `bundle.*.json` from `/demo/preprocess/locales/`
      - [x] `<meta name="app-root" content="/demo/preprocess/">` in `index.html`
    - [x] Entrypoints
      - [x] `polymer build` to serve at `/`
      - [x] `polymer build --entrypoint demo/preprocess/index.html` to serve at `/demo/preprocess/`
    - [x] Targets
      - [x] `build/esm-unbundled`
      - [x] `build/esm-bundled`
      - [x] `build/es6-bundled`
      - [x] `build/es5-bundled`
- [x] Class syntax (`i18n-element`) support
  - [ ] TBD...
- [x] Preprocess
  - [x] Legacy
  - [x] Class (`html` template literal)
- [x] Bundle
- [x] Gulp tasks
  - [x] Preprocess
  - [x] Bundle
  - [ ] TBD...
- [x] Test (Legacy Syntax `Polymer({})` only)

| browser | raw | preprocessed | bundled | coverage |
|:---:|:---:|:---:|:---:|:---:|
| Chrome 71 | ✔︎ | ✔︎ | ✔︎ | ✔︎ |
| Firefox 64 | ✔︎ | ✔︎ | ✔︎ | ✔︎ |
| Safari 12 | ✔︎ | ✔︎ | ✔︎ | ✔︎ |
| Safari 9 | ✔︎ | ✔︎ | ✔︎ | ✔︎ |
| Edge 17 | ✔︎ | ✔︎ | ✔︎ | ✔︎ |
| IE 11 | ✔︎ | ✔︎ | ✔︎ | ✔︎ |

- [ ] Documentation
  - [x] README
  - [x] iron-component-page on gh-pages
  - [ ] Inline comments
    - [ ] API Docs in webcomponents.org
      - API not shown
    - [ ] TBD...

## Issues
- [x] I18N target attributes whose names are missing $ at the end are renamed but original attributes are not removed
  - Example: `<node attr="abc"></node>` -> `<node attr="abc" attr$="abc"></node>`
  - Since Polymer template parser overrides the original attributes, there are no effects on rendering
  - Still, templates which have just been preprocessed have redundant attributes, which can have side effects on other preprocessors (i.e. i18n-element/i18n.js for lit-html) 
- [x] Coverage is skipped for Sauce Labs due to the issue https://github.com/t2ym/web-component-tester-istanbul/issues/6
  - [x] Patch: Introduce a new `"client-event-fragment"` socket.io message to send large data with 64KB chunks in separate HTTP POST requests
    - https://github.com/t2ym/web-component-tester/commit/5f265e75cee7e7fb279ff9b3c8878f7eac69f5dd
      - The Sauce Labs support team reported the fix had finally been deployed.
      - [x] The patches have been reverted as the fix had been verified. 
- [x] Infinite loop on `templateDefaultLang` configuration as below:
```javascript
  _template: ((t) => { t.setAttribute("lang", "fr"); return t; })(html`...template...`)
```
  - Root Cause: `DomModule` registration is missing on construction

## Notes
- `importMeta` property is required to detect the correct paths for target components
  - It seems `importPath` property is missing in element from the legacy `Polymer({})` syntax
  - It is better to use `importPath` property instead of the raw `importMeta` property
    - Under investigation (Conversion of `i18n-element` and testing will be required for further investigation)
- ~~Server must support `.mjs` extension as JavaScript MIME type~~
  - [x] Planning to fork `deepcopy` package to support ES6 modules with `.js` extensions
- `wct-browser-legacy/browser.js` is patched
  - The script path `lodash/index.js` is replaced with `wct-browser-legacy/node_modules/lodash/index.js` so that the correct version is loaded
  - [x] `gulp patch-wct-browser-legacy` to patch 
- IE 11 is skipped in tests due to errors
  - [x] `func.name` is `undefined` in IE11
    - [x] Fix (`3.0.0-pre.2`) : `func.name || func.toString().replace(/^function ([^ \(]*)((.*|[\n]*)*)$/, '$1')`
  - [x] `this.text` object mutations are not flushed to annotations
    - [x] Partial Fix (`3.0.0-pre.2`) : `MutableDataBehavior` is required in IE11
  - [x] English text object is overwritten by localized test objects
    - [x] Root Cause: `deepcopy` on IE11 does not copy the root object due to incorrect detection of 'object' type in `type-detect` as `Array Iterator`.  `[][Symbol.iterator]()` with polyfilled `Symbol` is misintepreted
  - [x] Use `'deepcopy/dist/deepcopy.js'` from `github:t2ym/deepcopy.js#0.6.3-esm.1`
    - `deepcopy/dist/deepcopy.js` is an ES module indentical to `deepcopy/dist/deepcopy.mjs` to avoid currently uncommon `.mjs` extension
  - [ ] Skipping tests
    - [ ] `lang.raw` for `preference` test in `preference`
    - [ ] `lang.raw` for `preference` test in `no-persist`
    - [x] Works well in manual tests
    - [ ] `text` for `empty-element` in `edge-case`
    - [ ] Root Cause: under investigation
