### ISSUE TITLE
[4.0] Extract I18N interface without dependency on Polymer library

### ISSUE THREAD

**Issue by t2ym** [t2ym/i18n-behavior#72]
[4.0] Extract I18N interface without dependency on Polymer library

## Status
- Part of https://github.com/t2ym/i18n-element/issues/63
- WIP in [4.0-develop](https://github.com/t2ym/i18n-behavior/tree/4.0-develop) branch
- NPM package
  - `npm install i18n-behavior@next` or `npm install i18n-behavior@4.0.0-pre.19`
    - `@polymer/polymer` as a peer dependency
    - Compatible with `i18n-element@^4.0.0-pre`
    - Not compatible with `i18n-element@3.0.0`

## Tasks
- [x] Depend on `i18n-format@4.0.0-pre.*`
- [x] Remove Polymer dependency from `i18n-attr-repo`
  - [x] Convert to a vanilla web component
  - TBD
- [x] Remove Polymer dependency from `i18n-preference`
  - [x] Convert to a vanilla web component
  - [x] Remove `<iron-localstorage>` dependency from `i18n-preference`
  - [x] Re-implement `"storage"` event handler for the vanilla web component
  - TBD
- [x] Remove `<iron-ajax>` dependency from `I18nBehavior`
- [x] Extract Polymer-independent interfaces to `i18n-controller.js`
- [x] Move `@polymer/polymer` from dependencies to devDependencies
- [x] Drop Safari 9 support
- [ ] Documentation
  - [x] Decent comments
  - [ ] API Docs page
- TBD

## Design Issues
- [x] Polymer dependency as an NPM package
  - [x] As all users of `I18nBehavior` should depend on `@polymer/polymer` NPM package, it should be acceptable to move `@polymer/polymer` from `dependencies` to `devDependencies`
  - [x] `@polymer/polymer` should be added to `peerDependencies`
  - `i18n-element@4` package will depend on `i18n-behavior@4` but Polymer library will NOT be installed nor loaded unless an Polymer element, which depends on `@polymer/polymer` NPM package, imports `i18n-element@4` or `i18n-behavior@4`
  - This is not a normal configuration but should be practical
  - [x] There must be explicit documentation on this configuration to avoid any unexpected missing `@polymer/polymer` package errors
- [x] Are `importMeta` properties for `i18n-preference` and `i18n-attr-repo` required? No

## Issues
- [x] Fail to import `I18nBehavior@4.0.0-pre.12` via `import { I18nBehavior } from "i18n-behavior"`
  - Root Cause: the main module was changed to `i18n-controller.js` in `i18n-behavior@4.0.0-pre.12`
  - [x] Fix: The main module is reverted to `i18n-behavior.js` at `i18n-behavior@4.0.0-pre.13`

**Comment by t2ym** [comment]
## `i18n-behavior.js` is the main module again at `4.0.0-pre.13`
- Do not import `i18n-bahavior@4.0.0-pre.12` with `import { I18nBehavior } from "i18n-behavior"` omitting the script file name
- The main module of `i18n-behavior@4.0.0-pre.12` is `i18n-controller.js`

| i18n-behavior | Main Module | @polymer/polymer | Notes |
|:--|:--|:--|:--|
| `4.0.0-pre.13` | `i18n-behavior.js` | `peerDependencies` | |
| `4.0.0-pre.12` | `i18n-controller.js` | `devDependencies` | No `import "i18n-behavior"` |
| `4.0.0-pre.11` | `i18n-behavior.js` | `devDependencies` | |
